Traceback (most recent call last):
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fpath = "/gpfs/fs1/data/reddylab/Kuei/Dex_PROcap/run_homer/out_annotate/annoTSS/tss_count_raw.txt"
dat_raw = read_tsv(fpath)
head(dat_raw, 3)
------------------

Error: '/gpfs/fs1/data/reddylab/Kuei/Dex_PROcap/run_homer/out_annotate/annoTSS/tss_count_raw.txt' does not exist.
Traceback:

1. read_tsv(fpath)
2. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
 .     locale = locale, skip = skip, skip_empty_rows = skip_empty_rows, 
 .     comment = comment, n_max = n_max, guess_max = guess_max, 
 .     progress = progress)
3. standardise_path(file)
4. check_path(path)
5. stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
 .     getwd(), "')"), ".", call. = FALSE)
ERROR: Error: '/gpfs/fs1/data/reddylab/Kuei/Dex_PROcap/run_homer/out_annotate/annoTSS/tss_count_raw.txt' does not exist.


