Traceback (most recent call last):
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/data/reddylab/Kuei/envs/jupyterhub/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
suppressMessages(suppressWarnings(source("config.R")))
------------------

Error in file(filename, "r", encoding = encoding): cannot open the connection
Traceback:

1. suppressMessages(suppressWarnings(source("config.R")))
2. withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
3. suppressWarnings(source("config.R"))
4. withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
5. source("config.R")
6. file(filename, "r", encoding = encoding)
ERROR: Error in file(filename, "r", encoding = encoding): cannot open the connection


